// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
<<<<<<< HEAD
import "dotenv/config"
import { defineConfig } from "prisma/config"
=======
import "dotenv/config";
import { defineConfig } from "prisma/config";
>>>>>>> 4b23ec6 (feat: api-tests)

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
<<<<<<< HEAD
    url: process.env["DATABASE_URL"],
=======
    url: process.env.DATABASE_URL,
>>>>>>> 4b23ec6 (feat: api-tests)
  },
})
