export {
  authService,
  usersService,
  onboardingService,
  categoriesService,
  providersService,
  serviceRequestsService,
  notificationsService,
  offersService,
  jobsService,
  paymentsService,
  verificationService,
  remindersService,
  reviewsService,
} from "@/lib/mocks/services";
